version: '2'
services:
    redis:
        image: redis:latest
        command: [ "redis-server"]
    wikichron:
        build:
            context: .
            dockerfile: ./Dockerfile
        links:
            - redis
        ports:
            - 8080:8080
        volumes:
            - .:/wikichron/
            - /data/wiki_dumps/csv/:/data/wiki_dumps/csv/

